export const BG_COLOR = '#111'
export const GREEN_COLOR = '#F1D372'
export const GRAY_COLOR = '#AEAEAE'
export const TEXT_COLOR = '#fff'
export const INPUTS_BG = '#1F1F1F'
export const MUTE_TEXT = '#888888'